### ISSUE TITLE
Configure Build and Deployment to Heroku(?)

### ISSUE THREAD

**Issue by cjennison** [cjennison/penguin-planner#9]
Configure an auto deployment on merged changes to master/main to a **development deployment** of the tool. 

Decide on a deployment location. Heroku, Azure, AWS.
The build produces a minified package of files found in the build/ folder. The system merely needs to serve these files with index.html as an entry point.

The deployment is using create-react-app as a template. Refer to documentation for specifics if needed.

**Comment by rauvagol** [comment]
deployed to vercel by chris
